// This file is generated by Slice Machine. Update with care!

import EmailSignup from './EmailSignup';
import FullWidthImage from './FullWidthImage';
import HeadlineWithButton from './HeadlineWithButton';
import InfoWithImage from './InfoWithImage';
import TextInfo from './TextInfo';

export {
	EmailSignup,
	FullWidthImage,
	HeadlineWithButton,
	InfoWithImage,
	TextInfo,
};

export const components = {
	EmailSignup: EmailSignup,
	FullWidthImage: FullWidthImage,
	HeadlineWithButton: HeadlineWithButton,
	InfoWithImage: InfoWithImage,
	TextInfo: TextInfo,
};
